apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "pet", "namespace": "COE-MERN-STACK-DEMO", "kind": "DeploymentConfig"}]'
    name: petclinic-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/irfanjs/openshift.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic